import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { EmojiHappyIcon } from '@heroicons/react/solid'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen p-4 flex flex-col justify-center items-center bg-gray-900">
        <h1 className="text-6xl text-white">
          the win jar
          <EmojiHappyIcon className="inline h-10 w-10 mt-4 text-yellow-400"/>
        </h1>

        <p className="m-4 text-sm text-gray-400">
          coming soon!
        </p>
      </main>
    </div>
  )
}

export default Home
